name: adharris
pygments: true
permalink: pretty

jekyll_models: [series]
jekyll_models_urls: pretty

sass:
    syntax: scss        # scss|sass
    style:  nested  # nested|expanded|compact|compressed
