name: adharris
pygments: true
permalink: pretty

prose:
    siteurl: "https://adharris.net"
    rooturl: "_posts"

    metadata:
      _posts:
        - name: "Title"
          field:
            element: text
            label: Title
        - name: "categories"
          field:
            element: "hidden"
            value:
              - "post"
        - name: "layout"
          field:
            element: "select"
            label: "Layout"
            placeholder: "Select a layout"
            options:
              - name: "Default"
                value: "default"
              - name: "Blog Post"
                value: "post"


sass:
    syntax: scss        # scss|sass
    style:  nested  # nested|expanded|compact|compressed
